### ISSUE TITLE
Why did you link to the Python wrapper?

### ISSUE THREAD

**Issue by pboling** [wordtreefoundation/melisa#1]
Instead of the C++ project in the [README.md Line 1](https://github.com/wordtreefoundation/melisa/blob/master/README.md#L1)?

Python: https://pypi.python.org/pypi/marisa-trie/
C++: https://code.google.com/p/marisa-trie/

Was it unintentional?

**Comment by canadaduane** [comment]
It was kind of unintentional. But I did follow the python wrapper, or at
least used it as inspiration. So that's how it ended up there (by accident).

**Comment by pboling** [comment]
Cool! :)  That was my assumption.  So we have a parallel implementation to the Python, and are not connected to it aside from the common ancestor of the C++ library.

**Comment by canadaduane** [comment]
Exactly.

**Comment by pboling** [comment]
Fixed in #6
